Update awsAuth method to accept options, including Vault role
DaniGuardiola/node-vault pull request #1
Opened 2018-05-07 18:39 UTC by GeoffreyBooth

The `aws-auth` branch assumes that the name of the IAM role is identical to the name of the role in Vault. This isn’t necessarily the case.

This PR allows the `awsAuth` method to accept an options object, which currently has only one setting that can be specified: `vaultRole`, to define the name of the role to use when connecting to Vault. There’s no need to define the IAM role since that’s retrieved dynamically. The `awsAuth` method also looks for a `VAULT_ROLE` environment variable as a fallback. If the environment variable isn’t set, and the options object is undefined or lacks the `vaultRole` key, the current behavior remains.

I also added an example to the README.

2018-05-08 16:48 UTC, DaniGuardiola requested changes
Good! I think this addition is needed and helpful.

Just one coding style suggestion:

For conciseness I would implement the option by doing two things:

- Set `options` default as an empty object, by doing: `async (vault, options = {})`
- I would use the "short circuit" technique when setting the request prop: `request.role = options.vaultRole || process.env.VAULT_ROLE`

Let me know what you think.

2018-05-09 00:17 UTC, GeoffreyBooth commented
Sure, I’ve made the updates. We need to fallback on `node.role` since that’s the previous behavior, of using the AWS IAM role name.

2018-05-09 16:06 UTC, DaniGuardiola commented
Ah sure, makes sense. Thanks a lot @GeoffreyBooth ! I'm merging.

2018-05-09 16:06 UTC, DaniGuardiola approved these changes

2018-05-09 16:06 UTC, merged

2018-05-09 16:40 UTC, GeoffreyBooth commented
Great, thanks! Any chance we can get this merged into `node-vault` core and released onto NPM? I’d love to be able to install this from NPM proper rather than a GitHub link.

2018-05-09 17:09 UTC, DaniGuardiola commented
Well, the PR needs some love, and I don't have the time at the moment. Feel free to help with that, but don't worry, at some point @kr1sp1n and I will make sure it is released.